// Database types for Supabase
// This file will be auto-generated by running: npx supabase gen types typescript --local
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string // UUID
          display_name: string
          avatar_emoji: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          avatar_emoji?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_emoji?: string
          created_at?: string
          updated_at?: string
        }
      }
      level_definitions: {
        Row: {
          id: number
          level_number: number
          delta: number
          min_range: number
          max_range: number
          operations: string[]
          required_accuracy: number
          created_at: string
        }
        Insert: {
          id?: number
          level_number: number
          delta: number
          min_range?: number
          max_range?: number
          operations?: string[]
          required_accuracy?: number
          created_at?: string
        }
        Update: {
          id?: number
          level_number?: number
          delta?: number
          min_range?: number
          max_range?: number
          operations?: string[]
          required_accuracy?: number
          created_at?: string
        }
      }
      user_progress: {
        Row: {
          id: number
          user_id: string // UUID
          level_number: number
          is_unlocked: boolean
          is_completed: boolean
          best_score: number
          best_streak: number
          total_attempts: number
          total_correct: number
          last_played_at: string | null
          unlocked_at: string | null
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          user_id: string
          level_number: number
          is_unlocked?: boolean
          is_completed?: boolean
          best_score?: number
          best_streak?: number
          total_attempts?: number
          total_correct?: number
          last_played_at?: string | null
          unlocked_at?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          level_number?: number
          is_unlocked?: boolean
          is_completed?: boolean
          best_score?: number
          best_streak?: number
          total_attempts?: number
          total_correct?: number
          last_played_at?: string | null
          unlocked_at?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      game_sessions: {
        Row: {
          id: string // UUID
          user_id: string // UUID
          level_number: number
          score: number
          best_streak: number
          answers: Json
          completed_at: string
        }
        Insert: {
          id?: string
          user_id: string
          level_number: number
          score: number
          best_streak: number
          answers: Json
          completed_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          level_number?: number
          score?: number
          best_streak?: number
          answers?: Json
          completed_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
